# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 829)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 50, 930, 676))
        self.frame.setMinimumSize(QtCore.QSize(930, 676))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("border:none;\n"
"font: 16pt \"黑体\";\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.horizontalLayout_3.addWidget(self.pushButton_logout)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("#frame_3{\n"
"    background-color: rgb(65, 85, 127);\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(65, 85, 127);\n"
"    border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    font: 14pt \"幼圆\";\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(98, 125, 198)\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_DHCP = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_DHCP.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_DHCP.setObjectName("pushButton_DHCP")
        self.verticalLayout_2.addWidget(self.pushButton_DHCP)
        self.pushButton_ICMP = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_ICMP.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ICMP.setObjectName("pushButton_ICMP")
        self.verticalLayout_2.addWidget(self.pushButton_ICMP)
        self.pushButton_ARP = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_ARP.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ARP.setObjectName("pushButton_ARP")
        self.verticalLayout_2.addWidget(self.pushButton_ARP)
        self.pushButton_Control = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Control.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Control.setObjectName("pushButton_Control")
        self.verticalLayout_2.addWidget(self.pushButton_Control)
        self.pushButton_MAC = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_MAC.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_MAC.setObjectName("pushButton_MAC")
        self.verticalLayout_2.addWidget(self.pushButton_MAC)
        self.pushButton_Window = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Window.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Window.setObjectName("pushButton_Window")
        self.verticalLayout_2.addWidget(self.pushButton_Window)
        self.pushButton_Person = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Person.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Person.setObjectName("pushButton_Person")
        self.verticalLayout_2.addWidget(self.pushButton_Person)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-left-radius:20px;\n"
"    border-bottom-left-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_DHCP = QtWidgets.QWidget()
        self.page_DHCP.setObjectName("page_DHCP")
        self.pushButton_DHCP_get = QtWidgets.QPushButton(self.page_DHCP)
        self.pushButton_DHCP_get.setGeometry(QtCore.QRect(260, 60, 191, 41))
        self.pushButton_DHCP_get.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_DHCP_get.setObjectName("pushButton_DHCP_get")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_DHCP)
        self.textBrowser.setGeometry(QtCore.QRect(60, 280, 581, 301))
        self.textBrowser.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_Address = QtWidgets.QTextBrowser(self.page_DHCP)
        self.textBrowser_Address.setGeometry(QtCore.QRect(60, 140, 581, 111))
        self.textBrowser_Address.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textBrowser_Address.setObjectName("textBrowser_Address")
        self.stackedWidget.addWidget(self.page_DHCP)
        self.page_ICMP = QtWidgets.QWidget()
        self.page_ICMP.setObjectName("page_ICMP")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_ICMP)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 40, 461, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border:None;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.page_ICMP)
        self.lineEdit.setGeometry(QtCore.QRect(260, 130, 311, 41))
        self.lineEdit.setStyleSheet("    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_ICMP)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 130, 121, 41))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border:None;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_ICMP)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 200, 121, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border:None;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_Power_in = QtWidgets.QLineEdit(self.page_ICMP)
        self.lineEdit_Power_in.setGeometry(QtCore.QRect(260, 200, 311, 41))
        self.lineEdit_Power_in.setStyleSheet("    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);")
        self.lineEdit_Power_in.setObjectName("lineEdit_Power_in")
        self.pushButton_ICMPstart = QtWidgets.QPushButton(self.page_ICMP)
        self.pushButton_ICMPstart.setGeometry(QtCore.QRect(210, 270, 291, 51))
        self.pushButton_ICMPstart.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_ICMPstart.setObjectName("pushButton_ICMPstart")
        self.textEdit_ICMPover = QtWidgets.QTextEdit(self.page_ICMP)
        self.textEdit_ICMPover.setGeometry(QtCore.QRect(110, 350, 481, 101))
        self.textEdit_ICMPover.setStyleSheet("font: 16pt \"幼圆\";")
        self.textEdit_ICMPover.setObjectName("textEdit_ICMPover")
        self.stackedWidget.addWidget(self.page_ICMP)
        self.page_ARP = QtWidgets.QWidget()
        self.page_ARP.setObjectName("page_ARP")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_ARP)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 60, 451, 121))
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 13pt \"黑体\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px")
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_GatewayIP = QtWidgets.QLineEdit(self.page_ARP)
        self.lineEdit_GatewayIP.setGeometry(QtCore.QRect(250, 230, 351, 51))
        self.lineEdit_GatewayIP.setStyleSheet("    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);")
        self.lineEdit_GatewayIP.setObjectName("lineEdit_GatewayIP")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_ARP)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 230, 131, 51))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border:None;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_ARP)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 300, 161, 51))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border:None;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_MisleadIP = QtWidgets.QLineEdit(self.page_ARP)
        self.lineEdit_MisleadIP.setGeometry(QtCore.QRect(250, 300, 351, 51))
        self.lineEdit_MisleadIP.setStyleSheet("    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);")
        self.lineEdit_MisleadIP.setObjectName("lineEdit_MisleadIP")
        self.pushButton_ARPstart = QtWidgets.QPushButton(self.page_ARP)
        self.pushButton_ARPstart.setGeometry(QtCore.QRect(250, 380, 221, 51))
        self.pushButton_ARPstart.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_ARPstart.setObjectName("pushButton_ARPstart")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_ARP)
        self.stackedWidget_3.setGeometry(QtCore.QRect(120, 460, 461, 80))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_12.setGeometry(QtCore.QRect(90, 0, 301, 71))
        self.pushButton_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"幼圆\";\n"
"border:None")
        self.pushButton_12.setObjectName("pushButton_12")
        self.stackedWidget_3.addWidget(self.page_6)
        self.stackedWidget.addWidget(self.page_ARP)
        self.page_Control = QtWidgets.QWidget()
        self.page_Control.setObjectName("page_Control")
        self.pushButton_Controlstart = QtWidgets.QPushButton(self.page_Control)
        self.pushButton_Controlstart.setGeometry(QtCore.QRect(430, 500, 221, 51))
        self.pushButton_Controlstart.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_Controlstart.setObjectName("pushButton_Controlstart")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_Control)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 380, 601, 81))
        self.pushButton_13.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 13pt \"黑体\";\n"
"border-radius:10px;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_Controlget = QtWidgets.QLineEdit(self.page_Control)
        self.lineEdit_Controlget.setGeometry(QtCore.QRect(60, 500, 351, 51))
        self.lineEdit_Controlget.setStyleSheet("    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);")
        self.lineEdit_Controlget.setObjectName("lineEdit_Controlget")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_Control)
        self.pushButton_14.setGeometry(QtCore.QRect(50, 70, 601, 81))
        self.pushButton_14.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 13pt \"黑体\";\n"
"border-radius:10px;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_Controlin = QtWidgets.QLineEdit(self.page_Control)
        self.lineEdit_Controlin.setGeometry(QtCore.QRect(60, 190, 351, 51))
        self.lineEdit_Controlin.setStyleSheet("    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);")
        self.lineEdit_Controlin.setObjectName("lineEdit_Controlin")
        self.pushButton_Controlopen = QtWidgets.QPushButton(self.page_Control)
        self.pushButton_Controlopen.setGeometry(QtCore.QRect(430, 190, 221, 51))
        self.pushButton_Controlopen.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_Controlopen.setObjectName("pushButton_Controlopen")
        self.stackedWidget.addWidget(self.page_Control)
        self.page_MAC = QtWidgets.QWidget()
        self.page_MAC.setObjectName("page_MAC")
        self.lineEdit_MACget = QtWidgets.QLineEdit(self.page_MAC)
        self.lineEdit_MACget.setGeometry(QtCore.QRect(140, 170, 401, 51))
        self.lineEdit_MACget.setStyleSheet("font: 14pt \"Yu Gothic UI Semilight\";")
        self.lineEdit_MACget.setObjectName("lineEdit_MACget")
        self.pushButton_MACstart = QtWidgets.QPushButton(self.page_MAC)
        self.pushButton_MACstart.setGeometry(QtCore.QRect(140, 260, 401, 51))
        self.pushButton_MACstart.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_MACstart.setObjectName("pushButton_MACstart")
        self.textEdit_MACover = QtWidgets.QTextEdit(self.page_MAC)
        self.textEdit_MACover.setGeometry(QtCore.QRect(100, 350, 481, 101))
        self.textEdit_MACover.setStyleSheet("font: 12pt \"幼圆\";")
        self.textEdit_MACover.setObjectName("textEdit_MACover")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_MAC)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 40, 461, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border:None;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_MAC)
        self.page_Window = QtWidgets.QWidget()
        self.page_Window.setObjectName("page_Window")
        self.pushButton_IPalive = QtWidgets.QPushButton(self.page_Window)
        self.pushButton_IPalive.setGeometry(QtCore.QRect(450, 60, 151, 51))
        self.pushButton_IPalive.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_IPalive.setObjectName("pushButton_IPalive")
        self.lineEdit_IPalive = QtWidgets.QLineEdit(self.page_Window)
        self.lineEdit_IPalive.setGeometry(QtCore.QRect(60, 60, 331, 51))
        self.lineEdit_IPalive.setStyleSheet("font: 13pt \"幼圆\";")
        self.lineEdit_IPalive.setObjectName("lineEdit_IPalive")
        self.lineEdit_IPalive_2 = QtWidgets.QLineEdit(self.page_Window)
        self.lineEdit_IPalive_2.setGeometry(QtCore.QRect(60, 340, 241, 51))
        self.lineEdit_IPalive_2.setObjectName("lineEdit_IPalive_2")
        self.lineEdit_Portalive = QtWidgets.QLineEdit(self.page_Window)
        self.lineEdit_Portalive.setGeometry(QtCore.QRect(320, 340, 71, 51))
        self.lineEdit_Portalive.setObjectName("lineEdit_Portalive")
        self.pushButton_Portalive = QtWidgets.QPushButton(self.page_Window)
        self.pushButton_Portalive.setGeometry(QtCore.QRect(450, 340, 151, 51))
        self.pushButton_Portalive.setStyleSheet("QPushButton{\n"
"    border:2px solid black;\n"
"    border-radius:7px;\n"
"    font: 14pt \"幼圆\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(234, 234, 234)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_Portalive.setObjectName("pushButton_Portalive")
        self.textEdit = QtWidgets.QTextEdit(self.page_Window)
        self.textEdit.setGeometry(QtCore.QRect(60, 130, 541, 151))
        self.textEdit.setStyleSheet("font: 14pt \"Yu Gothic UI Semilight\";\n"
"border:2px solid black;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_Window)
        self.textEdit_2.setGeometry(QtCore.QRect(60, 410, 541, 171))
        self.textEdit_2.setStyleSheet("font: 14pt \"Yu Gothic UI Semilight\";\n"
"border:2px solid black;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.stackedWidget.addWidget(self.page_Window)
        self.page_SQL = QtWidgets.QWidget()
        self.page_SQL.setObjectName("page_SQL")
        self.stackedWidget.addWidget(self.page_SQL)
        self.page_Person = QtWidgets.QWidget()
        self.page_Person.setObjectName("page_Person")
        self.frame_8 = QtWidgets.QFrame(self.page_Person)
        self.frame_8.setGeometry(QtCore.QRect(110, 80, 501, 471))
        self.frame_8.setMinimumSize(QtCore.QSize(501, 471))
        self.frame_8.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_P_pass1 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_P_pass1.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_P_pass1.setText("")
        self.lineEdit_P_pass1.setObjectName("lineEdit_P_pass1")
        self.verticalLayout_3.addWidget(self.lineEdit_P_pass1)
        self.lineEdit_P_pass2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_P_pass2.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_P_pass2.setText("")
        self.lineEdit_P_pass2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_P_pass2.setObjectName("lineEdit_P_pass2")
        self.verticalLayout_3.addWidget(self.lineEdit_P_pass2)
        self.pushButton_P_sure = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_P_sure.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_P_sure.setStyleSheet("font: 16pt \"幼圆\";")
        self.pushButton_P_sure.setObjectName("pushButton_P_sure")
        self.verticalLayout_3.addWidget(self.pushButton_P_sure)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 14pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 14pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setStyleSheet("font: 14pt \"Agency FB\";\n"
"color:rgb(0, 85, 255)")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_2.addWidget(self.page_4)
        self.verticalLayout_3.addWidget(self.stackedWidget_2)
        self.stackedWidget.addWidget(self.page_Person)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(7)
        self.stackedWidget_2.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.pushButton_3.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "网络仿真攻击渗透测试"))
        self.pushButton_DHCP.setText(_translate("MainWindow", "DHCP运行测试"))
        self.pushButton_ICMP.setText(_translate("MainWindow", "ICMP泛洪攻击"))
        self.pushButton_ARP.setText(_translate("MainWindow", "ARP欺骗攻击"))
        self.pushButton_Control.setText(_translate("MainWindow", "SSH远程控制"))
        self.pushButton_MAC.setText(_translate("MainWindow", "MAC欺骗攻击"))
        self.pushButton_Window.setText(_translate("MainWindow", "主机与端口扫描"))
        self.pushButton_Person.setText(_translate("MainWindow", "个人信息管理"))
        self.pushButton_DHCP_get.setText(_translate("MainWindow", "开始检测"))
        self.pushButton_5.setText(_translate("MainWindow", "请打开WireShark与eNSP仿真环境进行该测试"))
        self.lineEdit.setText(_translate("MainWindow", "ICMP泛洪攻击"))
        self.pushButton_6.setText(_translate("MainWindow", "攻击方式："))
        self.pushButton_7.setText(_translate("MainWindow", "攻击强度："))
        self.lineEdit_Power_in.setPlaceholderText(_translate("MainWindow", "请输入数字"))
        self.pushButton_ICMPstart.setText(_translate("MainWindow", "开始测试"))
        self.textEdit_ICMPover.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'幼圆\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "ARP攻击通过伪造IP地址和MAC地址实现ARP欺骗，\n"
"能够在网络中产生大量的ARP通信量，\n"
"攻击者只要持续不断的发出伪造的ARP响应包\n"
"就能更改目标主机ARP缓存中的IP-MAC条目，\n"
"造成网络中断或中间人攻击。"))
        self.lineEdit_GatewayIP.setPlaceholderText(_translate("MainWindow", " 输入你要冒充的设备IP"))
        self.pushButton_9.setText(_translate("MainWindow", "Gateway IP:"))
        self.pushButton_10.setText(_translate("MainWindow", "Misleading IP:"))
        self.lineEdit_MisleadIP.setPlaceholderText(_translate("MainWindow", " 输入你要欺骗的设备的IP"))
        self.pushButton_ARPstart.setText(_translate("MainWindow", "开始欺骗"))
        self.pushButton_12.setText(_translate("MainWindow", "正在欺骗\n"
"请打开WireShark和靶机进行验证"))
        self.pushButton_Controlstart.setText(_translate("MainWindow", "开始控制"))
        self.pushButton_13.setText(_translate("MainWindow", "【反向木马】目标主机作为主控端，本机作为被控端\n"
"请打开VMware虚拟机查看主控端IP地址并运行主控端程序\n"
"（请保证主控端与被控端在同一网络）"))
        self.lineEdit_Controlget.setPlaceholderText(_translate("MainWindow", "请输入主控端IP地址进行连接："))
        self.pushButton_14.setText(_translate("MainWindow", "【正向木马】目标主机作为被控端，本机作为主控端\n"
"主控端程序生效后，请打开VMware虚拟机运行被控端程序\n"
"（请保证主控端与被控端在同一网络）"))
        self.lineEdit_Controlin.setPlaceholderText(_translate("MainWindow", "请输入被控端IP地址进行连接："))
        self.pushButton_Controlopen.setText(_translate("MainWindow", "开始控制"))
        self.lineEdit_MACget.setPlaceholderText(_translate("MainWindow", "请输入冒充的MAC地址："))
        self.pushButton_MACstart.setText(_translate("MainWindow", "开始欺骗"))
        self.pushButton_4.setText(_translate("MainWindow", "请打开WireShark与eNSP仿真环境进行该测试"))
        self.pushButton_IPalive.setText(_translate("MainWindow", "开始检测"))
        self.lineEdit_IPalive.setPlaceholderText(_translate("MainWindow", "请输入需要检测的目标主机IP地址："))
        self.lineEdit_IPalive_2.setPlaceholderText(_translate("MainWindow", "请输入需要检测的目标IP地址："))
        self.lineEdit_Portalive.setPlaceholderText(_translate("MainWindow", "端口号："))
        self.pushButton_Portalive.setText(_translate("MainWindow", "开始检测"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Semilight\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Yu Gothic UI Semilight\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.lineEdit_P_pass1.setPlaceholderText(_translate("MainWindow", "密码："))
        self.lineEdit_P_pass2.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.pushButton_P_sure.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "账号或密码不能为空！"))
        self.label_2.setText(_translate("MainWindow", "两次输入密码不一致！"))
        self.label_3.setText(_translate("MainWindow", "密码修改成功！"))
import res_rc
